apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend
  namespace: onlinebookstore
spec:
  type: LoadBalancer
  selector:
    app: bookstore-frontend
  ports:
    - port: 80
      name: bookstore-frontend