version: "3.8"

services:
  frontend:
    build:
      context: ./frontend-bookstore
    container_name: bookstore-frontend
    ports:
      - "80:80"
    depends_on:
      - webapp
    networks:
      - front-tier
      - back-tier

  webapp:
    build:
      context: ./server
    container_name: bookstore-backend
    expose:
      - "3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/onlinebookstore
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - back-tier
  
  mongodb:
    image: mongo:latest
    container_name: bookstore-mongodb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db:rw
    networks:
      - back-tier

volumes:
  db-data:
    external: false

networks:
  back-tier: {}
  front-tier: {}
