version: "3.8"

services:
  frontend:
    build:
      context: ./frontend-bookstore
    container_name: bookstore-frontend
    volumes:
      - ./frontend-bookstore:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_HOST=bookstore-backend
      - PORT=3000
    # ports:
    #   - "80:80"
    ports:
      - "3000:3000"
    depends_on:
      - webapp
    networks:
      - front-tier
      - back-tier

  webapp:
    build:
      context: ./server
    container_name: bookstore-backend
    volumes:
      - ./server:/app
      - /app/node_modules
    # expose:
    #   - "3000"
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://bookstore-mongodb:27017/onlinebookstore
      - PORT=3000
      - JWT_SECRET=super_secret_key_123
      - JWT_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRE=15m
      - REFRESH_TOKEN_EXPIRE=7d
    depends_on:
      - mongodb
    networks:
      - back-tier

  mongodb:
    image: mongo:latest
    container_name: bookstore-mongodb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db:rw
    networks:
      - back-tier

volumes:
  db-data:
    external: false

networks:
  back-tier: {}
  front-tier: {}
