version: '2'
services:
  webapp:
    image: myonlinebookstore.azurecr.io/master/backend-server:55
    expose:
      - "80"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/onlinebookstore
    depends_on:
      - mongodb
    networks:
      - back-tier

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
      - mongodb
    networks:
      - back-tier

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db:rw
    networks:
      - back-tier

volumes:
  db-data:
    external: false

networks:
  back-tier: {}